version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
      - image: circleci/openjdk:8-jdk-node

    environment:
      - JEKYLL_ENV=production
    steps:
      - checkout
      - restore_cache:
          key: jekyll-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install library dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: jekyll-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run:
          name: Build site
          command: bundle exec jekyll build --incremental true
      - run:
          name: Install OpenJRE
          command: sudo apt-get install --assume-yes openjdk-8-jre

      - run:
          name: Deploy to s3
          command: s3_website push