source 'https://rubygems.org'

#gem "rack"
#gem "json"
gem "jekyll"
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "jekyll-archives"
gem "jekyll-feed"
gem "sprockets", "~> 3.7"
gem "sass"
gem "uglifier"
gem "kramdown"
gem "rouge"
gem "tzinfo-data"
gem "webrick"
gem "rexml"
gem "kramdown-parser-gfm"